add extract

diff --git a/download b/download
--- a/download
+++ b/download
@@ -4,6 +4,10 @@ if [ ! -d "libs" ]; then
     mkdir libs
 fi
 
+if [ ! -d "debs" ];  then
+    mkdir debs
+fi
+
 SOURCE="https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc"
 # Use the source below if you feel slow, or change it on your own.
 # SOURCE="http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/"
@@ -23,49 +27,34 @@ usage() {
 
 download_single() {
   local id=$1
+  local deb_name=$LIBC_PREFIX$id.deb
+  local dbg_name=$LIBC_DBG_PREFIX$id.deb
   echo "Getting $id"
   if [ -d "libs/$id" ]; then
     die "  --> Downloaded before. Remove it to download again."
   fi
 
   # download binary package
-  local url="$SOURCE/$LIBC_PREFIX$id.deb"
+  local url="$SOURCE/$deb_name"
   echo "  -> Location: $url"
-  local tmp=`mktemp -d`
   echo "  -> Downloading libc binary package"
-  wget "$url" 2>/dev/null -O $tmp/pkg.deb || die "Failed to download package from $url"
+  wget "$url" 2>/dev/null -O debs/$deb_name || die "Failed to download package from $url"
   echo "  -> Extracting libc binary package"
 
-  pushd $tmp 1>/dev/null
-  ar x pkg.deb || die "ar failed"
-  tar xf data.tar.* || die "tar failed"
-  popd 1>/dev/null
-
   mkdir libs/$id
-  cp $tmp/lib/*/* libs/$id 2>/dev/null || cp $tmp/lib32/* libs/$id 2>/dev/null \
-    || die "Failed to save. Check it manually $tmp"
+  ./extract debs/$deb_name libs/$id
   echo "  -> Package saved to libs/$id"
 
-  rm -rf $tmp
   # download debug info package
-  local url="$SOURCE/$LIBC_DBG_PREFIX$id.deb"
+  local url="$SOURCE/$dbg_name"
   echo "  -> Location: $url"
-  local tmp=`mktemp -d`
   echo "  -> Downloading libc debug package"
-  wget "$url" 2>/dev/null -O $tmp/pkg.deb || die "Failed to download package from $url"
+  wget "$url" 2>/dev/null -O debs/$dbg_name || die "Failed to download package from $url"
   echo "  -> Extracting libc debug package"
 
-  pushd $tmp 1>/dev/null
-  ar x pkg.deb || die "ar failed"
-  tar xf data.tar.* || die "tar failed"
-  popd 1>/dev/null
-
   mkdir libs/$id/.debug
-  cp $tmp/usr/lib/debug/lib/*/* libs/$id/.debug 2>/dev/null || cp $tmp/usr/lib/debug/lib32/* libs/$id/.debug 2>/dev/null \
-    || die "Failed to save. Check it manually $tmp"
+  ./extract -d debs/$dbg_name libs/$id/.debug
   echo "  -> Package saved to libs/$id/.debug"
-
-  rm -rf $tmp
 }
 
 if [[ $# != 1 ]]; then
