extract soft link

diff --git a/extract b/extract
--- a/extract
+++ b/extract
@@ -18,14 +18,10 @@ extract() {
         mkdir $out
     fi
     local tmp=`mktemp -d`
-    cp $deb $tmp/pkg.deb
-    pushd $tmp 1>/dev/null
-    ar x pkg.deb || die "ar failed"
-    tar xf data.tar.* || die "tar failed"
-    popd 1>/dev/null
-    
-    cp $tmp/lib/*/* $out 2>/dev/null || cp $tmp/lib32/* $out 2>/dev/null \
-      || cp $tmp/usr/lib/debug/lib/*/* $out 2>/dev/null || cp $tmp/usr/lib/debug/lib32/* $out 2>/dev/null \
+    dpkg -x $deb $tmp || die "dpkg failed"
+
+    cp -P $tmp/lib/*/* $out 2>/dev/null || cp -P $tmp/lib32/* $out 2>/dev/null \
+      || cp -P $tmp/usr/lib/debug/lib/*/* $out 2>/dev/null || cp -P $tmp/usr/lib/debug/lib32/* $out 2>/dev/null \
       || die "Failed to save. Check it manually $tmp"
     
     rm -rf $tmp
